document.write('<html><head><title>Jolty\'s Joint</title>');
document.write('<link rel="stylesheet" type="text/css" href="css/main.css" />');
document.write('</head><body style="background-attachment: fixed">');
document.write('<table border="0" width="57">');
document.write('<tr><td width="51">');
document.write('<a class="style39" href="index.jsp">');
document.write('<font color="#919E2D">Home</font></a>');
document.write('<a class="style39 style40" href="crypto.htm">');
document.write('<font color="#FF6600">Crypto</font></a>');
document.write('<a class="style40" href="games.htm">');
document.write('<font color="#000080">Games</font></a>');
document.write('<a href="../../pensieve/index.jsp" class="style40">');
document.write('<font color="#800080">Pensieve</font></a>');
document.write('<font color="#00FF00">');
document.write('<a class="style39" href="poker.htm">');
document.write('<font color="#00FF00">Poker</font></a></font>');
document.write('<a class="style39" href="../../golf/index.jsp">');
document.write('<font color="#C0C0C0">Golf</font></a></td>');
document.write('<td><iframe frameborder="0" marginwidth="0" marginheight="0" border="0" style="border:0;margin:0;width:728px;height:90px;" src="http://www.google.com/uds/modules/elements/newsshow/iframe.html?rsz=large&amp;format=728x90&amp;q=Golf&amp;element=true" scrolling="no" allowtransparency="true"></iframe>');
document.write('</td></tr></table>');