--\i "C:\Documents and Settings\joe\My Documents\workspace\sports\db\insert_teams.sql"
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('ATL', 'Atlanta','Falcons','NFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('WAS','Washington','Redskins','NFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('CHI','Chicago','Bears','NFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('ARI','Arizona','Cardinals','NFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('CIN','Cincinnati','Bengals','AFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('BAL','Baltimore','Ravens','AFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('IND','Indianapolis','Colts','AFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('HOU','Houston','Texans','AFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('JAX','Jacksonville','Jaguars','AFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('KAN','Kansas City','Chiefs','AFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('NWE','New England','Patriots','AFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('MIA','Miami','Dolphins','AFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('TAM','Tampa Bay','Buccaneers','NFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('GNB','Green Bay','Packers','NFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('NOR','New Orleans','Saints','NFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('CAR','Carolina','Panthers','NFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('SEA','Seattle','Seahawks','NFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('DET','Detroit','Lions','NFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('NYG','New York','Giants','NFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('SDG','San Diego','Chargers','AFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('SFO','San Francisco','49ers','NFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('TEN','Tennessee','Titans','AFC South');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('PHI','Philadelphia','Eagles','NFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('DAL','Dallas','Cowboys','NFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('DEN','Denver','Broncos','AFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('PIT','Pittsburgh','Steelers','AFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('BUF','Buffalo','Bills','AFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('CLE','Cleveland','Browns','AFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('MIN','Minnesota','Vikings','NFC North');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('NYJ','New York','Jets','AFC East');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('OAK','Oakland','Raiders','AFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('STL','St. Louis','Rams','NFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('RAM','Los Angeles','Rams','NFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('RAI','Los Angeles','Raiders','AFC West');
INSERT INTO NFL.TEAMS(team_code, team_city, team_nickname, division) VALUES ('PHO','Phoenix','Cardinals','NFC East');